version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
# docker-compose up -d
# docker exec -it postgres bash
# psql -U postgres
# psql \i fileName.pgsql
